# Regular fields
int8 i8
uint8 ui8

int16 i16
uint16 ui16

int32 i32
uint32 ui32

int64 i64
uint64 ui64

float32 f32
float64 f64

string s

time t
duration d

Nested n

Enum8 e8
Enum16 e16
Enum32 e32
Enum64 e64

# Fixed array fields
int8[2] ai8
uint8[2] aui8

int16[4] ai16
uint16[4] aui16

int32[8] ai32
uint32[8] aui32

int64[16] ai64
uint64[16] aui64

float32[4] af32
float64[8] af64

string[4] as

time[8] at
duration[8] ad

Nested[4] an

Enum8[8] ae8
Enum16[16] ae16
Enum32[32] ae32
Enum64[64] ae64

# Vector fields
int8[] vi8
uint8[] vui8

int16[] vi16
uint16[] vui16

int32[] vi32
uint32[] vui32

int64[] vi64
uint64[] vui64

float32[] vf32
float64[] vf64

string[] vs

time[] vt
duration[] vd

Nested[] vn

Enum8[] ve8
Enum16[] ve16
Enum32[] ve32
Enum64[] ve64

